services:
  pr_service:
    build: ./
    container_name: pr_service
    command: ./pr-service
    ports:
      - "8080:8080"
    depends_on:
      pr_postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito
      - POSTGRES_HOST=pr_postgres
      - POSTGRES_PORT=5432
    restart: unless-stopped

  pr_postgres:
    image: postgres:16
    container_name: pr_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
